//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReclutamientoRH.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReclutamientoRHEntities : DbContext
    {
        public ReclutamientoRHEntities()
            : base("name=ReclutamientoRHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidato> Candidatos { get; set; }
        public virtual DbSet<CandidatosSabenIdioma> CandidatosSabenIdiomas { get; set; }
        public virtual DbSet<CandidatosTienenCompetencia> CandidatosTienenCompetencias { get; set; }
        public virtual DbSet<Capacitacione> Capacitaciones { get; set; }
        public virtual DbSet<Competencia> Competencias { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<ExperienciaLaboral> ExperienciaLaborals { get; set; }
        public virtual DbSet<Idioma> Idiomas { get; set; }
        public virtual DbSet<Puesto> Puestos { get; set; }
    }
}
